# Generated by Django 4.2.2 on 2023-06-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
